
server:
  port: 8080
spring:
  cloud:
    gateway:
      routes:
        - id: movie-service
          uri: lb://movie-service
          predicates:
            - Path=/movies/all
            - Path=/movies/**
        - id: catalog-service
          uri: lb://catalog-service
          predicates:
            - Path=/catalog/**
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true

eureka:
  instance:
    hostname: localhost
    prefer-ip-address: true
  client:
    service-url:
      defaultZone: http://localhost:8761/
    fetch-registry: true
    register-with-eureka: true
 
management:
 endpoints:
   web:
     exposure:
       include: "*"
