management:
  endpoints:
    web:
      exposure:
        include: "*"
  health:
    circuitbreakers:
      enabled: true
  endpoint:
    health:
      enabled: true
      show-details: always
    shutdown:
      enabled: true
info:
  env:
    enabled: true


spring:
  zipkin:
    base-url: http://localhost:9411/
    enabled: true

  rabbitmq:
    username: user
    password: password
    host: localhost
    port: 5672

queue:
  movie:
    name: movieQueue
  serie:
    name: serieQueue
  catalog:
    name: catalogQueue


resilience4j:
  circuitbreaker:
    instances:
      review:
        allowHealthIndicatorToFail: false
        registerHealthIndicator: true
        slidingWindowType: COUNT_BASED
        slidingWindowSize: 5
        failureRateThreshold: 50
        waitDurationInOpenState: 15000
        permittedNumberOfCallsInHalfOpenState: 3
        automaticTransitionFromOpenToHalfOpenEnabled: true
  retry:
    instances:
      subscription:
        maxAttempts: 3
        waitDuration: 1000
        retryExceptions:
          - java.lang.IllegalArgumentException
