server:
  port: 8082

spring:
  data:
    mongodb:
      host: localhost
      port: 27017
      database: Netflix

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/

resilience4j:
  circuitbreaker:
    instances:
      review:
        allowHealthIndicatorToFail: false
        registerHealthIndicator: true
        slidingWindowType: COUNT_BASED
        slidingWindowSize: 5
        failureRateThreshold: 50
        waitDurationInOpenState: 15000
        permittedNumberOfCallsInHalfOpenState: 3
        automaticTransitionFromOpenToHalfOpenEnabled: true
  retry:
    instances:
      subscription:
        maxAttempts: 3
        waitDuration: 1000
        retryExceptions:
          - java.lang.IllegalArgumentException
