server:
  port : 8083

spring:
  data:
    mongodb:
      host: localhost
      port: 27017
      database: Netflix
  sleuth:
    sampler:
    probability: 1.0

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
